name: PyTest

on:
  workflow_call:
    inputs:
      python_version:
        description: 'Run with python version'
        type: string
        required: false
        default: "3.11"
  workflow_dispatch:
    inputs:
      python_version:
        description: 'Run with python version'
        type: string
        required: false
        default: "3.11"
        
jobs:
  pytest:
    name: PyTest Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ inputs.python_version }} Environment
        uses: kravchenkoda/hostsmate/.github/actions/python_setup@develop
        with:
          python_version: ${{ inputs.python_version }}

      - name: PyTest Code Coverage
        uses: kravchenkoda/hostsmate/.github/actions/pytest@develop
        with:
          codecov_token: ${{ secrets.CODECOV_TOKEN }}
