name: PyTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        sudo pip install pytest-cov
        sudo pip install freezegun
        sudo pip install -r requirements.txt
    - name: Analysing the code with pytest
      run: |
        #sudo pytest --cov=hostsmate/tests --cov-report=xml
        sudo pytest --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.codecov }}
        file: ./coverage.xml
